name: Release Linux AppImage
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: release-appimage-${{ github.ref }}
  cancel-in-progress: false

jobs:
  appimage-release:
    name: Build Release AppImage
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GNOME SDK
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.gnome.Sdk//49
      - name: Build AppImage
        env:
          CHRONOGRAPH_BUILD_ROOT: /tmp/chronograph-appimage
        run: ./build-aux/appimage/build.sh
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Chronograph-AppImage
          path: /tmp/chronograph-appimage/dist/*.AppImage
